# Model arguments
model_name_or_path: Meta-Llama/Meta-Llama-3.1-8B
tokenizer_name_or_path: Meta-Llama/Meta-Llama-3.1-8B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: true
bf16: true
tf32: true

# Dataset arguments
dataset_id_or_path: train_dataset.json
max_seq_length: 1024
packing: true
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
output_dir: data/llama-3-1-8b-math-orca-qlora

# LoRA arguments
use_peft: true
load_in_4bit: true
merge_adapter: false
lora_target_modules: "all-linear"
lora_r: 16
lora_alpha: 16

# Training arguments
num_train_epochs: 1
learning_rate: 2.0e-4 
lr_scheduler_type: constant
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42

# Hugging Face Hub 
push_to_hub: false
hub_model_id: llama-3-1-8b-math-orca-qlora
hub_strategy: every_save